version: '3.1'
services:
    jenkins-master:
        container_name: jenkins-master
        ports:
            - '8092:8080'
            - '50000:50000'
        image: jenkins-master
        volumes:
            - /srv/jenkins/home:/var/jenkins_home
    jenkins-slave:
        container_name: jenkins-slave
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins-master:8080'
        image: jenkins-slave
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - jenkins-master
    gitlab:
        container_name: gitlab
        restart: always
        ports:
            - '8093:80'
        image: gitlab/gitlab-ce:latest
        volumes:
             - /srv/gitlab/config:/etc/gitlab
             - /srv/gitlab/logs:/var/log/gitlab
             - /srv/gitlab/data:/var/opt/gitlab
    nexus:
         container_name: nexus
         restart: always
         image: sonatype/nexus3
         ports:
            - '8094:8081'
         volumes:
            - /srv/nexus/data:/nexus-data


